# ------------------------------
# Verdaccio Caching Proxy Config
# ------------------------------

storage: /verdaccio/storage

store:
  aws-s3:
    bucket: ${R2_BUCKET}
    region: auto
    accessKeyId: ${R2_ACCESS_KEY}
    secretAccessKey: ${R2_SECRET_KEY}
    endpoint: ${R2_ENDPOINT}
    s3ForcePathStyle: true

web:
  title: Verdaccio Cache Proxy

auth:
  htpasswd:
    max_users: 0

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '**':
    access: $all
    publish: $none
    unpublish: $none
    proxy: npmjs
    storage: aws-s3

log:
  type: stdout
  format: pretty
  level: http

listen: 0.0.0.0:4873

middlewares:
  audit:
    enabled: true